# This workflow will install Python dependencies, run tests with avariety of Python versions.
name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: List root directory
      run: ls -al

    - name: List requirements directory
      run: ls -al requirements

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/test_requirements.txt

    - name: Train pipeline
      run: |
        python titanic_model/train_pipeline.py

    - name: Test with pytest
      run: |
        pytest
